#!/bin/bash
#JAVA配置
JAVA_8_HOME=$(/usr/libexec/java_home -v1.8)
JAVA_7_HOME=$(/usr/libexec/java_home -v1.7)
JAVA_HOME=$JAVA_8_HOME
CLASSPATH=.:$JAVA_HOME/lib:$JAVA_HOME/jre/lib
export JAVA_HOME CLASSPATH

#本地shell脚本
PATH=$PATH:/Users/momo/local_bin
#mongodb
PATH=$PATH:/Users/momo/dev-tools/mongodb-osx-x86_64-3.4.4/bin
PATH=$PATH:/Users/momo/dev-tools/redis-3.2.9/src
#mariadb
PATH=$PATH:/usr/local/mariadb/mariadb-10.2.6-osx10.12-x86_64/bin
export PATH

#GNU Coreutils实现mac配色
if brew list | grep coreutils > /dev/null ; then
  PATH="$(brew --prefix coreutils)/libexec/gnubin:$PATH"
  alias ls='ls -F --show-control-chars --color=auto'
  eval `gdircolors -b $HOME/.dir_colors`
fi

#别名
alias l='ls'
alias la='ls -a'
alias ll='ls -lrt'

#修改终端提示符和颜色
#PS1="\[\e[31;40m\]\t:\W \$ "
PS1='\e[31;40m\]\t \e[32;40m\]\W\e[0m\] \$ '
export PS1
